### ISSUE TITLE
gametest http

### ISSUE THREAD

**Issue by nian0** [microsoft/minecraft-gametests#6]
How does the gametest framework use HTTP get requests? Is it the same as the native JS

**Comment by mammerla** [comment]
Within GameTest Framework, there isn't a way to make outbound HTTP requests or use resources available via an HTTP URL - your JS and other resources would need to be bundled within a resource pack.

**Comment by nian0** [comment]
> Within GameTest Framework, there isn't a way to make outbound HTTP requests or use resources available via an HTTP URL - your JS and other resources would need to be bundled within a behavior pack.

Can other packages be referenced? For example,
```
const fs = require('fs');
```
Or you need to put its source code in this directory for reference？
